<?php
/*
 * Copyright 2014 MailPlus
*
* Licensed under the Apache License, Version 2.0 (the "License"); you may not
* use this file except in compliance with the License. You may obtain a copy
* of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations
* under the License.
*/
$readDb = Mage::getSingleton('core/resource')->getConnection('core_write');
/* @var $readDb Varien_Db_Adapter_Pdo_Mysql */

//echo get_class($readDb);
//mailplus_bounces


$bounces = $readDb->fetchAll("SELECT * FROM mailplus_bounces");
$cols = array_keys(reset($bounces));


echo '<h1>Bounces</h1>';
echo '<p>No design yet</p>';

echo '<table width="100%">';
echo '<tr>';
foreach ( $cols as $col )
	echo "<th>$col</th>";
echo '</tr>';


foreach ( $bounces as $bounce )
{
	echo '<tr>';
	foreach ($bounce as $value)
		echo "<td>$value</td>";
	echo '</tr>';
}

echo '</table>';
?>