<?php
/*
 * Copyright 2014 MailPlus
*
* Licensed under the Apache License, Version 2.0 (the "License"); you may not
* use this file except in compliance with the License. You may obtain a copy
* of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations
* under the License.
*/
$mailplus = Mage::helper('mailplus');

$cronOftenStart = Mage::getModel('mailplus/info')->loadByName('cron_often_start');
$cronOftenEnd = Mage::getModel('mailplus/info')->loadByName('cron_often_end');
$cronHourlyStart = Mage::getModel('mailplus/info')->loadByName('cron_hourly_start');
$cronHourlyEnd = Mage::getModel('mailplus/info')->loadByName('cron_hourly_end');

function returnDateString($date) {
	$mailplus = Mage::helper('mailplus');
	$dateString = $mailplus->__("never");
	if ($date && $date->getValue()) {
		$dateString = date('Y-m-d H:i', $date->getValue());
	}
	return $dateString;
} 


$startStatus = returnDateString($cronOftenStart);
$endStatus = returnDateString($cronOftenEnd);
$hourlyStartStatus = returnDateString($cronHourlyStart);
$hourlyEndStatus = returnDateString($cronHourlyEnd);

?>
	<div class="content-header"><h3 class="icon-head"><?php echo $mailplus->__('MailPlus Cron status') ?></h3></div>
	
	<table>
		<tr>
			<th colspan="2">Cron often</th>	
		</tr>
	
		<tr>
			<td><?php echo $mailplus->__('Last started at') ?>:</td>
			<td><?php echo $startStatus ?></td>
		</tr>
		<tr>
			<td><?php echo $mailplus->__('Finished at') ?>:</td>
			<td><?php echo $endStatus ?></td>
		</tr>
				<tr>
			<th colspan="2">Cron hourly</th>	
		</tr>
	
		<tr>
			<td><?php echo $mailplus->__('Last started at') ?>:</td>
			<td><?php echo $hourlyStartStatus ?></td>
		</tr>
		<tr>
			<td><?php echo $mailplus->__('Finished at') ?>:</td>
			<td><?php echo $hourlyEndStatus ?></td>
		</tr>
		
	</table>



